title: Emily Geller
description: > # this means to ignore newlines until "baseurl:"
  Data Science in Seattle
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Emily Geller # add your name
author-img: emily-geller.jpg # add your photo
about-author: I'm a data scientist in Seattle, Washington. I love math, data and horchata.. and I'm always hungry to keep learning. # add description
twitter: emilyageller
facebook: emilyageller
github: emilyageller
linkedin: emily-geller
email: emilyageller@gmail.com
instagram: adailyfind

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
