title: Emily Geller
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Emily Geller # add your name
author-img: images/emily-geller.jpg # add your photo
about-author: I'm a data scientist in Seattle, Washington. Always hungry to keep learning. # add description
twitter: emilyageller# add your Twitter handle
facebook: # add your Facebook handle
github: emilyageller # add your Github handle
linkedin: emily-geller-94a17799# add your Linkedin handle
email: emilyageller@gmail.com# add your Email address
instagram: adailyfind

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
